### PR TITLE
Add more types of shapes with diff-updates

### PR DESCRIPTION
**Pull request by erkie**
@SamvelRaja this is in reference to the issue where we discussed marker diffing https://github.com/SamvelRaja/google-maps-addon/issues/27.

This includes some major changes in the API of the component.
- I moved out the `markerOptions` object and `infoWindow` object into separate properties
- Renamed `markerOptions` to just `markers`
- Refactored the `Helper`-mega object into smaller classes, and to be used as an instance instead
- Add `rectangles`, `circles` shapes as well
- Update README.md to reflect changes
- Make `key` attributes mandatory on all passed in objects, so we can diff and add new ones, update old ones and remove removed ones

Example usage is now for example: 

```
{{google-maps-addon mapOptions=mapOptions markers=markers}}
```

With this comes a lot of flexibility and the ability to easily add more objects, like Polygons and PolyLines. We can also add a lot more lifetime callbacks to the objects, like `onCreate`, `onUpdate` and `onRemove` which provides loads of flexibility. We can also animate changes because we always only update changed attributes.

What do you think? I have tried it out in our projects and it works very well and is nice to work with.

### CODE REVIEW

**Comment by erkie** [comment]
@SamvelRaja would love to hear your thoughts on this. :)

**Comment by SamvelRaja** [comment]
@erkie kindly merge it on your own and let me know. please make sure the tests are passing :p

**Comment by erkie** [comment]
Thanks @SamvelRaja. Tests pass now! Merging

**Comment by SamvelRaja** [comment]
@erkie  will update npm by this week end.
It would be better if you can specify your email to add as contributer in npm as well

**Comment by erkie** [comment]
Cool! My npm email is erik.rothoff@gmail.com

**Comment by SamvelRaja** [comment]
@erkie  i tried adding as you as collabarator in npm to allow you to publish by yourself, but i couldn't get your username for it.

**Comment by erkie** [comment]
My npm username is erikrothoff if it helps. Thanks!

**Comment by SamvelRaja** [comment]
Added you as collaborator, should be reflected within 24hrs from now

**Pull request merged**
